- name: Taint master node if workers available
  become: true
  command: |
    kubectl taint nodes {{ ansible_hostname }} CriticalAddonsOnly:NoSchedule --overwrite
  when: groups['workers'] | length > 0

- name: Add NFS provider as default storage class
  become: true
  template:
    src: nfs-storage.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/nfs-storage.yaml
    mode: 0600

- name: Make local-storage provider non-default storage class
  become: true
  lineinfile: 
    path: /var/lib/rancher/k3s/server/manifests/local-storage.yaml
    regexp: '^    storageclass.kubernetes.io/is-default-class: "true"$' 
    line: '    storageclass.kubernetes.io/is-default-class: "false"'

- name: Install Traefik custom config
  become: true
  template:
    src: traefik-config.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
    mode: 0600
