---
- name: Initial setup
  hosts: nodes
  gather_facts: false
  tags: ['pi-initial-setup']

  collections:
    - community.general

  roles:
    - role: pi-initial-setup

- name: Configure the master node
  hosts: master
  gather_facts: false
  tags: ['install-k3s-master']

  roles:
    - role: install-k3s-master

- name: Configure the worker nodes
  hosts: workers
  gather_facts: false
  tags: ['install-k3s-workers']

  roles:
    - role: install-k3s-workers

- name: Configure NFS server
  hosts: nfs
  gather_facts: false
  tags: ['install-nfs-server']
  
  roles:
    - role: install-nfs-server

- name: Configure cluster
  hosts: master
  gather_facts: true

  collections:
    - community.kubernetes
  
  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  
  roles:
    - role: basic-cluster-setup
      tags: ['basic-cluster-setup']
    
    - role: install-cert-manager
      tags: ['install-cert-manager']
