---
- name: Get Helm install script
  become: true
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Install Helm
  become: true
  command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm

- name: Remove Helm installer
  become: true
  file:
    path: /tmp/get_helm.sh
    state: absent

- name: Add prometheus-community chart repo
  become: true
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Deploy last Kube Prometheus stack version
  become: true
  kubernetes.core.helm:
    name: kube-prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    atomic: true
    values: "{{ lookup('template', 'kube-prometheus.yaml.j2') | from_yaml }}"
    update_repo_cache: true

- name: Deploy last Prometheus adapter version
  become: true
  kubernetes.core.helm:
    name: prometheus-adapter
    chart_ref: prometheus-community/prometheus-adapter
    release_namespace: monitoring
    create_namespace: true
    atomic: true
    values: "{{ lookup('template', 'prometheus-adapter.yaml.j2') | from_yaml }}"
    update_repo_cache: true

- name: Add falcosecurity  chart repo
  become: true
  kubernetes.core.helm_repository:
    name: falcosecurity
    repo_url: "https://falcosecurity.github.io/charts"

- name: Deploy Falco v0.37.1
  become: true
  kubernetes.core.helm:
    name: falco
    chart_ref: falcosecurity/falco
    chart_version: 4.3.1
    release_namespace: falco
    create_namespace: true
    atomic: true
    values: "{{ lookup('template', 'falco.yaml.j2') | from_yaml }}"
    update_repo_cache: true

- name: Deploy Falco exporter 0.8.3
  become: true
  kubernetes.core.helm:
    name: falco-exporter
    chart_ref: falcosecurity/falco-exporter
    chart_version: 0.11.0
    release_namespace: monitoring
    create_namespace: true
    atomic: true
    values: "{{ lookup('template', 'falco-exporter.yaml.j2') | from_yaml }}"
    update_repo_cache: true

- name: Deploy custom Grafana dashboard for cluster overview
  become: true
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'grafana-dashboard-kubernetes-cluster-dashboard.yaml.j2') | from_yaml }}"

- name: Deploy custom Grafana dashboard for Falco
  become: true
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'grafana-dashboard-falco.yaml.j2') | from_yaml }}"
