- name: Install nfs-kernel-server
  become: yes
  package:
    name: nfs-kernel-server
    state: present

- name: Create a share directory if it does not exists
  file:
    path: '{{ nfs_share  }}'
    state: directory
    mode: '0755'

- name: Update NFS shares
  become: yes
  lineinfile:
    dest: /etc/exports
    line: "{{ nfs_share }}{% for node in groups['nodes'] %} {{ node }}(rw,fsid=0,all_squash,sync,no_subtree_check,anonuid=1000,anongid=1000){% endfor %}"
  notify: load-exports
