---
- name: Install NFS server
  hosts: localhost
  connection: local
  gather_facts: false
  remote_user: pi
  vars_files:
    - vars.yml
  
  handlers:
    - name: load-exports
      become: yes
      ansible.builtin.shell:
        cmd: exportfs -ra

  tasks:
  - name: Install nfs-kernel-server
    become: yes
    package:
      name: nfs-kernel-server
      state: present

  - name: Create a share directory if it does not exists
    file:
      path: '{{ nfs_share  }}'
      state: directory
      mode: '0755'
  
  - name: Configure NFS
    become: yes
    lineinfile:
      dest: /etc/exports
      line: '{{ exports_line }}' 
    notify: load-exports
