- name: Disable Wifi and Bluetooth
  become: true
  lineinfile:
    dest: /boot/config.txt
    line: "{{ item.line }}"
  loop:
    - { line: 'dtoverlay=pi3-disable-wifi' }
    - { line: 'dtoverlay=pi3-disable-bt' }
  notify: reboot-pi
  
- name: Ensure apparmor and apparmor-utils are installed
  become: true
  apt:
    name: 
      - apparmor
      - apparmor-utils
    state: present
    update_cache: true
  notify: reboot-pi

- name: Ensure apparmor is enabled in cmdline.txt
  become: true
  replace:
    path: /boot/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
    - "apparmor=1"
    - "security=apparmor"
  notify: reboot-pi

- name: Disable sudo without password
  become: true
  file:
    path: /etc/sudoers.d/010_pi-nopasswd
    state: absent

- name: Set the right timezone
  become: true
  timezone:
    name: '{{ timezone }}'

- name: Secure pi home folder
  file:
    path: /home/pi
    state: directory
    mode: '0750'

- name: Disable SSH root access and password auth
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "{{ item.line }}"
  loop:
    - { line: 'PermitRootLogin no' }
    - { line: 'UsePAM no' }
    - { line: 'PasswordAuthentication no' }
  notify: reload-sshd
