---
- name: Get cert-manager manifests
  become: true
  get_url:
    url: https://github.com/jetstack/cert-manager/releases/download/{{ certmanager_version }}/cert-manager.yaml
    dest: /var/lib/rancher/k3s/server/manifests/cert-manager
    mode: '0600'

- name: Modify the manifest for arm
  become: true
  replace:
    path: /var/lib/rancher/k3s/server/manifests/cert-manager
    regexp: '(image:.*):(v.*)$'
    replace: '\1-arm:\2'

- name: Install cert-manager as addon
  become: true
  command: mv /var/lib/rancher/k3s/server/manifests/cert-manager /var/lib/rancher/k3s/server/manifests/cert-manager.yaml

- name: Install letsencrypt cluster issuer as addon
  become: true
  template:
    src: letsencrypt.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/letsencrypt.yaml

- name: Install letsencrypt-staging cluster issuer as addon
  become: true
  template:
    src: letsencrypt-staging.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/letsencrypt-staging.yaml

- name: Install letsencrypt-cloudflare cluster issuer as addon
    block:
      - name: Install cloudflare token secret
        template:
          src: cloudflare-api-token.yaml.j2
          dest: /var/lib/rancher/k3s/server/manifests/cloudflare-api-token.yaml
        
      - name: Install letsencrypt-cloudflare cluster issuer
        template:
          src: letsencrypt-cloudflare.yaml.j2
          dest: /var/lib/rancher/k3s/server/manifests/letsencrypt-cloudflare.yaml
    when: cloudflare_email != "" and cloudflare_token != ""
    become: true
