---
- name: Initial setup
  hosts: nodes
  gather_facts: false

  collections:
    - community.general

  roles:
    - role: pi-initial-setup
      tags: ['pi-initial-setup']

- name: Configure the master node
  hosts: master
  gather_facts: false

  roles:
    - role: install-k3s-master
      tags: ['install-k3s-master']

- name: Configure the worker nodes
  hosts: workers
  gather_facts: false

  roles:
    - role: install-k3s-workers
      tags: ['install-k3s-workers']

- name: Configure NFS server
  hosts: localhost
  gather_facts: false

  collections:
    - community.general
    - community.kubernetes
  
  environment:
    # The location of the kubeconfig file in the local machine
    K8S_AUTH_KUBECONFIG: ~/.kube/config
  
  roles:
    - role: install-nfs-server
      tags: ['install-nfs-server']
