---
- name: Initial setup
  hosts: nodes
  remote_user: pi
  become: yes

  tasks:
  - name: Disable Wifi
    lineinfile:
      path: /boot/config.txt
      line: dtoverlay=pi3-disable-wifi
    register: wifi_conf

  - name: Disable Bluetooth
    lineinfile:
      path: /boot/config.txt
      line: dtoverlay=pi3-disable-bt
    register: bluetooth_conf

  - name: Disable sudo without password
    file:
      path: /etc/sudoers.d/010_pi-nopasswd
      state: absent

  - name: Disable SSH root access and password auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      line: "{{ item.line }}"
    loop:
      - { line: 'PermitRootLogin no' }
      - { line: 'UsePAM no' }
      - { line: 'PasswordAuthentication no' }
    register: ssh_conf

  - name: Reload SSH service if needed
    ansible.builtin.service:
      name: sshd
      state: reloaded
    when: ssh_conf.changed

  - name: Reboot hosts if necessary
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami
    when: wifi_conf.changed or bluetooth_conf.changed
