---
- name: Initial setup
  hosts: nodes
  remote_user: pi
  become: yes
  gather_facts: no
  
  handlers:
    - name: reboot-pi
      reboot:
    - name: reload-sshd
      ansible.builtin.service:
        name: sshd
        state: reloaded

  tasks:
  - name: Disable Wifi and Bluetooth
    lineinfile:
      dest: /boot/config.txt
      line: "{{ item.line }}"
    loop:
      - { line: 'dtoverlay=pi3-disable-wifi' }
      - { line: 'dtoverlay=pi3-disable-bt' }
    register: ssh_conf
    notify: reboot-pi

  - name: Disable sudo without password
    file:
      path: /etc/sudoers.d/010_pi-nopasswd
      state: absent

  - name: Set the right timezone (For me at least)
    community.general.timezone:
      name: Europe/Madrid

  - name: Disable SSH root access and password auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      line: "{{ item.line }}"
    loop:
      - { line: 'PermitRootLogin no' }
      - { line: 'UsePAM no' }
      - { line: 'PasswordAuthentication no' }
    notify: reload-sshd
