- name: Get master taints
  become: true
  shell: |
    kubectl describe node '{{ master_node_name }}' | grep Taint | awk '{print $2}'
  args:
    executable: /bin/bash
  register: master_taints

- name: Taint master node
  become: true
  command: "kubectl taint nodes {{ master_node_name }} CriticalAddonsOnly:NoSchedule"
  when: "{{ node_token_output.stdout_lines[0] }} == <none>"
