- name: Ensure cgroups are configured correctly in cmdline.txt
  become: true
  replace:
    path: /boot/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
  notify: reboot-pi

- name: Ensure openshift Python library is installed.
  pip:
    name: openshift
    state: present
  become: true

- name: Download K3s install script
  become: true
  get_url:
    url: https://get.k3s.io
    dest: "~/k3s_install.sh"
    mode: a+x

- name: Install K3s control plane (takes a while)
  become: true
  shell: >-
    ~/k3s_install.sh --no-deploy metrics-server,traefik >> ~/k3s_install_log.txt
  args:
    chdir: "~"
    creates: /var/lib/rancher/k3s/server/node-token

- name: Get node token
  become: true
  command: cat /var/lib/rancher/k3s/server/node-token
  register: node_token_output

- name: Set node_token fact
  set_fact:
    node_token: "{{ node_token_output.stdout_lines[0] }}"
